### ISSUE TITLE
TypeError: Path must be a string. Received undefined at assertPath (path.js:7:11)

### ISSUE THREAD

**Issue by jaredthirsk** [MeirionHughes/aurelia-cli-electron-app#18]
Followed the instructions.  Step 2: running.  Assert fail:

```
$ au run --watch
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
Finished 'configureEnvironment'
Starting 'buildTypeScript'...
Finished 'processMarkup'
Finished 'processCSS'
Finished 'buildTypeScript'
Starting 'writeBundles'...
Tracing app...
Tracing environment...
Tracing main...
Tracing elements/dock-panel...
Tracing elements/index...
Tracing elements/menu-control...
Tracing elements/tab-control...
Tracing elements/window...
Tracing models/page...
Tracing pages/example-page...
Tracing app...
Tracing app...
Tracing elements/dock-panel...
Tracing elements/dock-panel...
Tracing elements/menu-control...
Tracing elements/menu-control...
Tracing elements/tab-control...
Tracing elements/tab-control...
Tracing elements/window...
Tracing elements/window...
Tracing pages/example-page...
Tracing aurelia-bootstrapper...
Tracing aurelia-history...
Tracing aurelia-history-browser...
Tracing aurelia-loader-default...
Tracing aurelia-logging-console...
Tracing aurelia-pal-browser...
Tracing aurelia-route-recognizer...
Tracing aurelia-router...
Tracing aurelia-templating-binding...
Tracing text...
Tracing aurelia-templating-router...
Tracing aurelia-testing...
Writing app-bundle.js...
Writing vendor-bundle.js...
Finished 'writeBundles'
Starting 'watch'...

App threw an error during load
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at module.exports (D:\dev2\experiments\aurelia-cli-electron-app\node_modules\electron-reload\main.js:15:23)
    at Object.<anonymous> (D:\dev2\experiments\aurelia-cli-electron-app\index.js:5:27)
    at Object.<anonymous> (D:\dev2\experiments\aurelia-cli-electron-app\index.js:31:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by jaredthirsk** [comment]
Readme says requires nodejs 6.  Is that at least 6 or exactly 6?  I am using v.7.5.0 on Windows.


```
$ node --version
v7.5.0

```

**Comment by MeirionHughes** [comment]
hmm, might be you're on a newer Aurelia CLI and something has broken with this project - I don't use Aurelia CLI anymore. Probably needs re-generating the aurelia project folder via CLI.

**Comment by dotnetrules** [comment]
I'm having the same problem.

**Comment by seishin4real** [comment]
the dependency version is: "aurelia-cli": "^0.21.0",
which is installed locally (I uninstalled the global one)
and I still get this error

**Comment by seishin4real** [comment]
omg, jaw-dropped...
add  "main": "index.js" to your package.json
